### PR TITLE
Fix Validator From Reporting False Positives

### LINKED ISSUE #540: Fix Validator
Validator doesn't work on unipig.exchange. It also doesn't work locally for validating the transactions of multiple accounts. Fix this please.

### PR DESCRIPTION
**Pull request by willmeister**
##  Description
Fixes validator hex/decimal issue with slot calculation that was causing it to report fraud when transactions were not fraudulent. 

Also adds more logging for insight into validation and Merkle tree operations.

### Fixes
- Fixes #540 

## Contributing Agreement

- [x] I have read and understood the [Plasma Group Contributing Guide and Code of Conduct](https://github.com/plasma-group/pigi/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

File: packages/wallet/src/rollup-state-machine.ts [hunk 1]
```diff
@@ -376,18 +372,27 @@ export class DefaultRollupStateMachine implements RollupStateMachine {
       MerkleTreeInclusionProof,
       string
     ] = await this.lock.acquire(DefaultRollupStateMachine.lockKey, async () => {
-      const bigKey: BigNumber = new BigNumber(key)
+      const bigKey: BigNumber = new BigNumber(key, 10)
```
Comment (karlfloersch) [inline packages/wallet/src/rollup-state-machine.ts]: Oooo
